name: setup
runs:
  using: composite
  steps:
    - uses: actions/setup-node@6
      with:
        node-version: 24
        cache: yarn
    - run: corepack enable
      shell: bash
    - run: yarn --immutable
      shell: bash
